// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_Lv81BZPgKq0OnhonAH4Ae0OrJtlNGg',
    appId: '1:713200207963:web:ed6fa65f7760eb4382177e',
    messagingSenderId: '713200207963',
    projectId: 'ctse-lab-exam',
    authDomain: 'ctse-lab-exam.firebaseapp.com',
    databaseURL: 'https://ctse-lab-exam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ctse-lab-exam.appspot.com',
    measurementId: 'G-1LD0ZWQZV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDwXQ7vrvGlnGmQjGDXkIpCjeHFQc6bO0',
    appId: '1:713200207963:android:3dff25bc04ef708382177e',
    messagingSenderId: '713200207963',
    projectId: 'ctse-lab-exam',
    databaseURL: 'https://ctse-lab-exam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ctse-lab-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68Pn-Xuohtjc38HE9FkyFNleE-DdR040',
    appId: '1:713200207963:ios:ba398daf9078699782177e',
    messagingSenderId: '713200207963',
    projectId: 'ctse-lab-exam',
    databaseURL: 'https://ctse-lab-exam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ctse-lab-exam.appspot.com',
    iosClientId: '713200207963-8ebcsqugjnioq4c7ap0ecgomc04n4210.apps.googleusercontent.com',
    iosBundleId: 'com.flashminat0.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68Pn-Xuohtjc38HE9FkyFNleE-DdR040',
    appId: '1:713200207963:ios:ba398daf9078699782177e',
    messagingSenderId: '713200207963',
    projectId: 'ctse-lab-exam',
    databaseURL: 'https://ctse-lab-exam-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ctse-lab-exam.appspot.com',
    iosClientId: '713200207963-8ebcsqugjnioq4c7ap0ecgomc04n4210.apps.googleusercontent.com',
    iosBundleId: 'com.flashminat0.firebaseflutter',
  );
}
